### ISSUE TITLE
`gem install lingua-ruby` fails

### ISSUE THREAD

**Issue by BillBrower-Shopify** [followerstracker/lingua-ruby#1]
Running `gem install lingua-ruby` on Mac OS X Sonoma 14.5, Ruby 3.2.1, and `gem` 3.5.1 results in this error:

```
  --- stderr
  Using bindgen with clang args: ["-I/opt/rubies/3.2.1/include/ruby-3.2.0", "-I/opt/rubies/3.2.1/include/ruby-3.2.0/arm64-darwin22", "-fms-extensions", "-fdeclspec", "-O3", "-fno-fast-math", "-ggdb3", "-Wno-error=implicit-function-declaration", "-I/opt/homebrew/opt/openssl@1.1/include", "-I/opt/homebrew/opt/readline/include", "-I/opt/homebrew/opt/libyaml/include", "-I/opt/homebrew/opt/gdbm/include", "-D_XOPEN_SOURCE", "-D_DARWIN_C_SOURCE", "-D_DARWIN_UNLIMITED_SELECT", "-D_REENTRANT"]
  thread 'main' panicked at /Users/billbrower/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.56/src/fallback.rs:811:9:
  "union_(unnamed_at_/opt/rubies/3_2_1/include/ruby-3_2_0/ruby/internal/anyargs_h_271_1)" is not a valid Ident
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [target/release/liblingua.dylib] Error 101

make failed, exit code 2
```

**Comment by wvengen** [comment]
I'm seeing something similar on a Linux x86_64 system:
```
  --- stderr
Using bindgen with clang args: ["-I<rubydir>/include/ruby-3.3.0", "-I<rubydir>/include/ruby-3.3.0/x86_64-linux",
"-fms-extensions", "-O3", "-fno-fast-math", "-ggdb3", "-Wall", "-Wextra", "-Wdeprecated-declarations", "-Wdiv-by-zero", "-Wduplicated-cond", "-Wimplicit-function-declaration",
"-Wimplicit-int", "-Wpointer-arith", "-Wwrite-strings", "-Wold-style-definition", "-Wimplicit-fallthrough=0", "-Wmissing-noreturn", "-Wno-cast-function-type",
"-Wno-constant-logical-operand", "-Wno-long-long", "-Wno-missing-field-initializers", "-Wno-overlength-strings", "-Wno-packed-bitfield-compat", "-Wno-parentheses-equality",
"-Wno-self-assign", "-Wno-tautological-compare", "-Wno-unused-parameter", "-Wno-unused-value", "-Wsuggest-attribute=format", "-Wsuggest-attribute=noreturn", "-Wunused-variable",
"-Wmisleading-indentation", "-Wundef"]
  warning: unknown warning option '-Wduplicated-cond' [-Wunknown-warning-option]
  warning: unknown warning option '-Wimplicit-fallthrough=0'; did you mean '-Wimplicit-fallthrough'? [-Wunknown-warning-option]
  warning: unknown warning option '-Wno-packed-bitfield-compat'; did you mean '-Wno-padded-bitfield'? [-Wunknown-warning-option]
  warning: unknown warning option '-Wsuggest-attribute=format'; did you mean '-Wproperty-attribute-mismatch'? [-Wunknown-warning-option]
  warning: unknown warning option '-Wsuggest-attribute=noreturn' [-Wunknown-warning-option]
  clang diag: warning: unknown warning option '-Wduplicated-cond' [-Wunknown-warning-option]
  clang diag: warning: unknown warning option '-Wimplicit-fallthrough=0'; did you mean '-Wimplicit-fallthrough'? [-Wunknown-warning-option]
  clang diag: warning: unknown warning option '-Wno-packed-bitfield-compat'; did you mean '-Wno-padded-bitfield'? [-Wunknown-warning-option]
  clang diag: warning: unknown warning option '-Wsuggest-attribute=format'; did you mean '-Wproperty-attribute-mismatch'? [-Wunknown-warning-option]
  clang diag: warning: unknown warning option '-Wsuggest-attribute=noreturn' [-Wunknown-warning-option]
  thread 'main' panicked at <rust_1.82.0_dir>/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.56/src/fallback.rs:811:9:
  "__atomic_wide_counter_struct_(unnamed_at_/sr/include/x86_64-linux-gnu/bits/atomic_wide_counter_h_28_3)" is not a valid Ident
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
make: *** [Makefile:566: target/release/liblingua.so] Error 101

make failed, exit code 2
```

**Comment by wvengen** [comment]
When I checkout the lingua-ruby source tree, update the dependencies in `ext/lingua/Cargo.toml` to the current (langua 1.6.2, magnus 0.71), run `cargo update` then `rake install`, it is working for me.
